apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: app
  labels:
    app: backend
spec:
  containers:
  - image: subscriptionbox-be
    name: backend
    imagePullPolicy: Never
    ports:
    - containerPort: 3001
  dnsPolicy: ClusterFirst
  restartPolicy: Always
