apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001         # Port on which the service will be exposed
      targetPort: 3001   # Port on the backend Pod
  type: ClusterIP
